"use client";
import { useState } from "react";

const Q = [["garden", "bahçe", "A place where plants grow."], ["window", "pencere", "An opening that lets in light."], ["journey", "yolculuk", "Travel from one place to another."], ["quiet", "sakin", "Making very little noise."], ["remember", "hatırlamak", "To keep something in your mind."]] as const;

export function WordMatchDemo() {
  const [step, setStep] = useState(0); const [answer, setAnswer] = useState<string | null>(null); const [score, setScore] = useState(0);
  const reset = () => { setStep(0); setAnswer(null); setScore(0); };
  if (step === Q.length) return <section className="mx-auto max-w-[390px] rounded-[24px] border-[8px] border-[#D8C7CF] bg-[#F7F4EC] p-6 shadow-2xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#6B4355]">Oturum tamamlandı</p><h2 className="mt-2 text-[27px] font-bold leading-tight text-[#1C1B1A]">Güzel çalışma.</h2><p className="mt-2 text-[15px] leading-[21px] text-[#7A7672]">5 kelimeden {score} tanesini ilk denemede bildin.</p><a href="https://play.google.com/store/apps/details?id=com.krayirhanstudio.lingorise" target="_blank" rel="noopener noreferrer" className="mt-6 block rounded-[18px] bg-[#6B4355] px-4 py-3 text-center text-[15px] font-bold text-white">LingoRise&apos;ı indir ↗</a><button type="button" onClick={reset} className="mt-3 w-full text-[13px] font-semibold text-[#7A7672] hover:text-[#1C1B1A]">Tekrar çalış</button></section>;
  const [word, meaning, hint] = Q[step]; const options = [meaning, ...Q.filter((_, i) => i !== step).slice(0, 2).map((x) => x[1])]; const isCorrect = answer === meaning;
  return <section aria-labelledby="word-match-title" className="mx-auto max-w-[390px] rounded-[24px] border-[8px] border-[#D8C7CF] bg-[#F7F4EC] p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between text-[13px] font-semibold text-[#7A7672]"><span className="text-[#6B4355]">LingoRise</span><span>{step + 1} / 5</span></div><div className="flex gap-1">{Q.map((_, i) => <span key={i} className={`h-1 flex-1 rounded-full ${i <= step ? "bg-[#6B4355]" : "bg-[#E7E1D7]"}`} />)}</div><div className="mt-8"><p className="text-[11px] font-bold uppercase tracking-[0.12em] text-[#A8A49E]">İngilizce kelime</p><p id="word-match-title" className="mt-2 text-[31px] font-bold leading-9 tracking-tight text-[#1C1B1A]">{word}</p></div><div className="mt-6 space-y-3">{options.map((option) => <button key={option} type="button" disabled={Boolean(answer)} onClick={() => { setAnswer(option); if (option === meaning) setScore((s) => s + 1); }} className={`w-full rounded-[14px] border px-4 py-3 text-left text-[15px] font-medium transition ${answer && option === meaning ? "border-[#CDE2CA] bg-[#EAF3E8] text-[#2C6326]" : answer && option === answer ? "border-[#F3C5B8] bg-[#FCEEEA] text-[#8F3A22]" : "border-[#E7E1D7] bg-white text-[#1C1B1A] hover:border-[#D8C7CF]"}`}>{option}</button>)}</div><div className="mt-6 min-h-16" aria-live="polite">{answer && <div className="border-t border-[#E7E1D7] pt-4"><p className={`text-[15px] font-bold ${isCorrect ? "text-[#2C6326]" : "text-[#8F3A22]"}`}>{isCorrect ? "Doğru cevap." : `Doğru cevap: ${meaning}`}</p><p className="mt-1 text-[13px] leading-[18px] text-[#7A7672]">{hint}</p></div>}</div>{answer && <button type="button" onClick={() => { setStep((s) => s + 1); setAnswer(null); }} className="rounded-[18px] bg-[#6B4355] px-4 py-3 text-[15px] font-bold text-white">{step === 4 ? "Sonucu gör" : "Sonraki kelime"}</button>}</section>;
}
